# Generated by Django 4.0.3 on 2022-11-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0028_jobapplication_appliedtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
